version: "3.8"
services:
  backend:
    restart: always
    build:
      context: ../backend  # Flask 后端项目的路径
      dockerfile: Dockerfile
    ports:
      - 8000:8000  # 后端应用程序的端口映射
    depends_on:
      - mysql
  web:
    image: nginx
    container_name: my-web
    ports:
      - 80:80
    environment:
      - TZ=Asia/shanghai
    volumes:
      - .docker-volumes/nginx/config/nginx.conf:/etc/nginx/nginx.conf # 映射 nginx 配置
      - .docker-volumes/nginx/config/default.conf:/etc/nginx/conf.d/default.conf # 映射默认配置
      - ../web/dist:/usr/share/nginx/html # 映射静态代码
      - .docker-volumes/nginx_logs/http_ssl:/nginx_logs/http_ssl # 映射 http_ssl
    depends_on:
      - backend # 依赖 backend 服务
    restart: always
  mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3366:3306
    volumes:
      - .docker-volumes/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10